/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.MarerialDAO;
import Modelo.Constantes;
import Modelo.Material;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 * Tela que faz o registo de um material.
 * @author 
 * @version 1.0
 */
public class RegistarMaterial extends javax.swing.JFrame {

    private static final String STEP_CRIAR = "Criar";
    public static final String STEP_VISUALIZAR = "Visualizar";
    private static final String STEP_EDITAR = "Editar";

    /**
     * Creates new form
     */
    public RegistarMaterial() {
        initComponents();
         Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize = (int) tk.getScreenSize().getWidth();
                int ysize = (int) tk.getScreenSize().getHeight();
         this.setSize(xsize,ysize);
        readJTable();
        setStep(STEP_CRIAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblRegistarMaterial = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbtFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jcbNome = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jbtGravar = new javax.swing.JButton();
        jbtActualizar = new javax.swing.JButton();
        jbtEditar = new javax.swing.JButton();
        jbtRemover = new javax.swing.JButton();
        jbrPesquisar = new javax.swing.JButton();
        jbtLimpar = new javax.swing.JButton();
        jbtVoltar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        lblRegistarMaterial.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        lblRegistarMaterial.setText("REGISTO DO MATERIAL");
        jPanel8.add(lblRegistarMaterial);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridLayout(3, 0));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridLayout(0, 10));
        jPanel10.add(jLabel2);
        jPanel10.add(jLabel3);
        jPanel10.add(jLabel4);
        jPanel10.add(jLabel5);
        jPanel10.add(jLabel6);
        jPanel10.add(jLabel7);
        jPanel10.add(jLabel8);
        jPanel10.add(jLabel9);
        jPanel10.add(jLabel10);

        jbtFechar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtFechar.setText("Fechar");
        jbtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharActionPerformed(evt);
            }
        });
        jPanel10.add(jbtFechar);

        jPanel9.add(jPanel10);

        jPanel7.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        jPanel2.setLayout(new java.awt.BorderLayout());

        lblNome.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblNome.setText("Nome");

        lblCodigo.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblCodigo.setText("Codigo");

        jtfCodigo.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jtfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusLost(evt);
            }
        });
        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });
        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyPressed(evt);
            }
        });

        jcbNome.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jcbNome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livro", "Apagador", "DataShow", "Cabo de Rede", "Cabo de Corrente", "Cabo de Video", "Mouse" }));
        jcbNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbNomeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(jcbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Quantidade", "Data"
            }
        ));
        tabela.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jbtGravar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtGravar.setText("Gravar");
        jbtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGravarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtGravar);

        jbtActualizar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtActualizar.setText("Actualizar");
        jbtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtActualizar);

        jbtEditar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtEditar.setText("Editar");
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtEditar);

        jbtRemover.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtRemover.setText("Remover");
        jbtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoverActionPerformed(evt);
            }
        });
        jPanel4.add(jbtRemover);

        jbrPesquisar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbrPesquisar.setText("Pesquisar");
        jbrPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrPesquisarActionPerformed(evt);
            }
        });
        jPanel4.add(jbrPesquisar);

        jbtLimpar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtLimpar.setText("Limpar");
        jbtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimparActionPerformed(evt);
            }
        });
        jPanel4.add(jbtLimpar);

        jbtVoltar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtVoltar.setText("Voltar");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtVoltar);

        jPanel6.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * butao responsavel por limpar os dados na tela
     * @param evt 
     */
    private void jbtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimparActionPerformed
        // TODO add your handling code here:
            int b = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar?");
            if (b == 0) {
                jcbNome.setSelectedIndex(0);
                jtfCodigo.setText(null);
                jtextFieldSemFoco();
                readJTable();
            }
    }//GEN-LAST:event_jbtLimparActionPerformed

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void jtfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyPressed

        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jbtGravar.requestFocus();
        }
    }//GEN-LAST:event_jtfCodigoKeyPressed

    /**
     * butao responsavel por gravar os dados na base dados.
     * @param evt 
     */
    private void jbtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGravarActionPerformed
        // TODO add your handling code here:
        Material b = new Material();

        MarerialDAO estu = new MarerialDAO();

        int contador = 0;
        for (Material a : estu.consular()) {
            if (a.getCodigo().equalsIgnoreCase(jtfCodigo.getText())) {
                contador++;
            }
        }
        if (contador == 0) {

            b.setNome((String) jcbNome.getSelectedItem());
            b.setCodigo(jtfCodigo.getText().toUpperCase());
            b.setQuantidade(1);
            b.setEstado(Constantes.ESTADO_REGISTO_VIGOR);
            b.setData(new Date());
            estu.gravar(b);
            JOptionPane.showMessageDialog(null, "O material foi registado com sucesso");
            jcbNome.setSelectedIndex(0);
            jtfCodigo.setText(null);

            readJTable();
        } else {
            JOptionPane.showMessageDialog(null, "O Codigo introduzido ja foi registado.");
        }

    
    }//GEN-LAST:event_jbtGravarActionPerformed

    /**
     * butao responsavel por actualizar dados que ja foram gravados na base de dados.
     * @param evt 
     */
    private void jbtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizarActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            Material b = new Material();

            MarerialDAO estu = new MarerialDAO();
      
                b.setNome((String) jcbNome.getSelectedItem());
                b.setCodigo((String)tabela.getValueAt(tabela.getSelectedRow(), 0));
                b.setQuantidade(1);
                b.setData((Date) tabela.getValueAt(tabela.getSelectedRow(), 3));

               if( estu.atualizar(b)){
                JOptionPane.showMessageDialog(null, "O material foi actualizado com sucesso");
                jcbNome.setSelectedIndex(0);
                jtfCodigo.setText(null);
                //jtextFieldSemFoco();
                readJTable();
                setStep(STEP_CRIAR);
            } else {
                JOptionPane.showMessageDialog(null, "Nao foi possivel actualizar o material!!!");
            }

        }
    }//GEN-LAST:event_jbtActualizarActionPerformed

    /**
     * butao responsavel por remover o objecto na base de dados de uma forma logica.
     * Na remocao muda o estudo do registo para removido
     * @param evt 
     */
    private void jbtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoverActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            Material a = new Material();
            MarerialDAO dau = new MarerialDAO();

            int b = JOptionPane.showConfirmDialog(null, "Deseja mesmo remover?");
            if (b == 0) {
                a.setNome((String) tabela.getValueAt(tabela.getSelectedRow(), 1));
                a.setCodigo((String) tabela.getValueAt(tabela.getSelectedRow(), 0));
                a.setQuantidade(1);
                a.setEstado(Constantes.ESTADO_REGISTO_REMOVIDO);
                a.setData((Date) tabela.getValueAt(tabela.getSelectedRow(), 3));

                dau.atualizar(a);
                JOptionPane.showMessageDialog(null,
                        "Removido com sucesso");
                jcbNome.setSelectedIndex(0);
                jtfCodigo.setText(null);
                
                readJTable();
                setStep(STEP_CRIAR);
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Selecione um material para poder remover");
        }
    }//GEN-LAST:event_jbtRemoverActionPerformed

    private void jbrPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrPesquisarActionPerformed
        // TODO add your handling code here:
        readJTable1();
    }//GEN-LAST:event_jbrPesquisarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            jcbNome.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            jtfCodigo.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            setStep(STEP_VISUALIZAR);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void tabelaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_tabelaAncestorAdded

    private void jcbNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbNomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfCodigo.requestFocus();
        }
    }//GEN-LAST:event_jcbNomeKeyPressed

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed
        // TODO add your handling code here:
        setStep(STEP_EDITAR);
    }//GEN-LAST:event_jbtEditarActionPerformed

    private void jbtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jbtFecharActionPerformed

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        // TODO add your handling code here:
        int b = JOptionPane.showConfirmDialog(null, "Deseja mesmo voltar?");
        if (b == 0) {
            new RegistarMaterial().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbtVoltarActionPerformed

    private void jtfCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfCodigo, "ex 123M");
    }//GEN-LAST:event_jtfCodigoFocusGained

    private void jtfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusLost
        // TODO add your handling code here:
        perderFoco(jtfCodigo, "ex 123M");
    }//GEN-LAST:event_jtfCodigoFocusLost

    /**
     * Metodo responsavel por buscar os dados na base de dados e mostrar na tabela.
     */
    public void readJTable() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        MarerialDAO dau = new MarerialDAO();

        for (Material a : dau.consular()) {
//            if ((a.getEstado().equalsIgnoreCase(Constantes.ESTADO_REGISTO_VIGOR))) {
                modelo1.addRow(new Object[]{a.getCodigo(), a.getNome(), a.getQuantidade(),
                    a.getData()

                });

//            }
        }
    }

    /**
     * Metodo responsavel buscar os dados pesquisados e mostrar na tabela.
     */
    public void readJTable1() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        MarerialDAO dau = new MarerialDAO();

        for (Material a : dau.consular()) {
            if (a.getNome().equalsIgnoreCase((String) jcbNome.getSelectedItem()) || (a.getCodigo().equalsIgnoreCase(jtfCodigo.getText())) || (a.getNome().equalsIgnoreCase((String) jcbNome.getSelectedItem()))) {

                modelo1.addRow(new Object[]{a.getCodigo(), a.getNome(),
                    a.getQuantidade(), a.getData()

                });
            }
        }
    }

    /**
     * metodo que ajuda a desabilitar alguns campos e butoes na tela.
     * @param step 
     */
    public void setStep(String step) {

        if (step.equalsIgnoreCase(STEP_CRIAR)) {
            jbtGravar.setVisible(true);
            jbrPesquisar.setVisible(true);
            jbtLimpar.setVisible(true);
            jbtActualizar.setVisible(false);
            jbtEditar.setVisible(false);
            jbtRemover.setVisible(false);
            jbtVoltar.setVisible(false);
            jtfCodigo.setEnabled(true);
            jcbNome.setEnabled(true);
           

        } else if (step.equalsIgnoreCase(STEP_VISUALIZAR)) {
            jbtGravar.setVisible(false);
            jbrPesquisar.setVisible(false);
            jbtLimpar.setVisible(false);
            jbtActualizar.setVisible(false);
            jbtEditar.setVisible(true);
            jbtRemover.setVisible(true);
            jbtVoltar.setVisible(true);
            jtfCodigo.setEnabled(false);
            jcbNome.setEnabled(false);

        } else if (step.equalsIgnoreCase(STEP_EDITAR)) {
            jbtGravar.setVisible(false);
            jbrPesquisar.setVisible(false);
            jbtLimpar.setVisible(true);
            jbtActualizar.setVisible(true);
            jbtEditar.setVisible(false);
            jbtRemover.setVisible(false);
            jbtVoltar.setVisible(false);
            jtfCodigo.setEnabled(false);
            jcbNome.setEnabled(true);
        }
    }
    
    private void ganharFocus(JTextField tf, String s) {
        if (tf.getText().equals(s)) {
            tf.setText("");
        }
    }

    private void perderFoco(JTextField tf, String s) {
        if (tf.getText().equals("")) {
            tf.setText(s);
        }
    }

    private void jtextFieldSemFoco() {
        jtfCodigo.setText("ex: 123M");

    }

public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
/*
Metódo para mudar o estilo da tela 
JTATO lookAndFeel usado
             */
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
                //                tema castanho para o Look and Feel
                UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                //                Tema do Java
                //            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
                //                Mudar o look and fell do JBuldier ide
                //                 UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
                //                   UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
                //       UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");

            



}

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAcesso.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        



} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAcesso.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        



} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAcesso.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        



} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAcesso.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistarMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbrPesquisar;
    private javax.swing.JButton jbtActualizar;
    private javax.swing.JButton jbtEditar;
    private javax.swing.JButton jbtFechar;
    private javax.swing.JButton jbtGravar;
    private javax.swing.JButton jbtLimpar;
    private javax.swing.JButton jbtRemover;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JComboBox<String> jcbNome;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRegistarMaterial;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
