/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ComputadorDAO;
import Modelo.Computador;
import Modelo.Constantes;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 * Tela que faz o registo de um computador.
 * @author 
 * @version 1.0
 */
public class RegistarComputador extends javax.swing.JFrame {

    private static final String STEP_CRIAR = "Criar";
    public static final String STEP_VISUALIZAR = "Visualizar";
    private static final String STEP_EDITAR = "Editar";

    /**
     * Creates new form
     */
    public RegistarComputador() {

        initComponents();
         Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize = (int) tk.getScreenSize().getWidth();
                int ysize = (int) tk.getScreenSize().getHeight();
         this.setSize(xsize,ysize);
        jtextFieldSemFoco();
        readJTable();
        setStep(STEP_CRIAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lblRegistoComputador = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbtFechar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jtfDescricao = new javax.swing.JTextField();
        jtfCodigo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        lblComponentes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistComponentes = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jbtGravar = new javax.swing.JButton();
        jbtActualizar = new javax.swing.JButton();
        jbtEditar = new javax.swing.JButton();
        jbtRemover = new javax.swing.JButton();
        jbtAvariado = new javax.swing.JButton();
        jbrPesquisar = new javax.swing.JButton();
        jbtLimpar = new javax.swing.JButton();
        jbtVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setMinimumSize(new java.awt.Dimension(860, 93));
        jPanel16.setPreferredSize(new java.awt.Dimension(1040, 93));
        jPanel16.setLayout(new java.awt.GridLayout(3, 0));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        lblRegistoComputador.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        lblRegistoComputador.setText("REGISTO DO COMPUTADOR");
        jPanel15.add(lblRegistoComputador);

        jPanel16.add(jPanel15);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new java.awt.GridLayout(0, 10));
        jPanel17.add(jLabel20);
        jPanel17.add(jLabel21);
        jPanel17.add(jLabel22);
        jPanel17.add(jLabel23);
        jPanel17.add(jLabel24);
        jPanel17.add(jLabel25);
        jPanel17.add(jLabel26);
        jPanel17.add(jLabel27);
        jPanel17.add(jLabel1);

        jbtFechar2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jbtFechar2.setText("Fechar");
        jbtFechar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFechar2ActionPerformed(evt);
            }
        });
        jPanel17.add(jbtFechar2);

        jPanel16.add(jPanel17);

        jPanel14.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel14);

        jPanel5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel5AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblDescricao.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblDescricao.setText("Descricao");

        lblCodigo.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblCodigo.setText("Codigo");

        jtfDescricao.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jtfDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfDescricaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDescricaoFocusLost(evt);
            }
        });
        jtfDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDescricaoActionPerformed(evt);
            }
        });
        jtfDescricao.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtfDescricaoPropertyChange(evt);
            }
        });
        jtfDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDescricaoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDescricaoKeyTyped(evt);
            }
        });

        jtfCodigo.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jtfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusLost(evt);
            }
        });
        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });
        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao))
                .addContainerGap())
        );

        jPanel6.setLayout(null);

        lblComponentes.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblComponentes.setText("Componentes");
        jPanel6.add(lblComponentes);
        lblComponentes.setBounds(50, 10, 160, 33);

        jlistComponentes.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jlistComponentes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Gabinete", "Monitor", "Cabo de Rede", "Cabo de Corrente", "Cabo de Video", "Teclado", "Mouse" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlistComponentes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlistComponentesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jlistComponentes);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(210, 0, 240, 210);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new java.awt.BorderLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descricao", "Componentes", "Data"
            }
        ));
        tabela.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jbtGravar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtGravar.setText("Gravar");
        jbtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGravarActionPerformed(evt);
            }
        });
        jbtGravar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtGravarKeyPressed(evt);
            }
        });
        jPanel4.add(jbtGravar);

        jbtActualizar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtActualizar.setText("Actualizar");
        jbtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtActualizar);

        jbtEditar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtEditar.setText("Editar");
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtEditar);

        jbtRemover.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtRemover.setText("Remover");
        jbtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoverActionPerformed(evt);
            }
        });
        jPanel4.add(jbtRemover);

        jbtAvariado.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtAvariado.setText("Avariado");
        jbtAvariado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAvariadoActionPerformed(evt);
            }
        });
        jPanel4.add(jbtAvariado);

        jbrPesquisar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbrPesquisar.setText("Pesquisar");
        jbrPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrPesquisarActionPerformed(evt);
            }
        });
        jPanel4.add(jbrPesquisar);

        jbtLimpar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtLimpar.setText("Limpar");
        jbtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimparActionPerformed(evt);
            }
        });
        jPanel4.add(jbtLimpar);

        jbtVoltar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtVoltar.setText("Voltar");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtVoltar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * butao responsavel por limpar os dados na tela
     * @param evt
     */
    private void jbtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimparActionPerformed
        // TODO add your handling code here:
        int b = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar?");
        if (b == 0) {
            jtfDescricao.setText(null);
            jtfCodigo.setText(null);
            jlistComponentes.setSelectedIndex(0);
            jtextFieldSemFoco();
            readJTable();
        }
    }//GEN-LAST:event_jbtLimparActionPerformed

    private void tabelaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaAncestorAdded
    /**
     * butao responsavel por gravar os dados na base dados.
     * @param evt 
     */
    private void jbtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGravarActionPerformed
        // TODO add your handling code here:
        ArrayList t = new ArrayList();
        Computador b = new Computador();
        ComputadorDAO estu = new ComputadorDAO();

        int[] selectedIx = this.jlistComponentes.getSelectedIndices();

        for (int i = 0; i < selectedIx.length; i++) {
            t.add(jlistComponentes.getModel().getElementAt(selectedIx[i]));

        }
          int contador = 0;
          
        for (Computador a : estu.consular()) {
            if (a.getCodigo().equalsIgnoreCase(jtfCodigo.getText())) {
                contador++;
            }
        }
        if (contador == 0) {
            b.setDescricao(jtfDescricao.getText());
            b.setCodigo(jtfCodigo.getText());
            b.setComponentes(t.toString());
            b.setEstado(Constantes.ESTADO_REGISTO_VIGOR);
            b.setData(new Date());

            estu.gravar(b);
            JOptionPane.showMessageDialog(null, "O computador foi registado com sucesso");
            jtfDescricao.setText(null);
            jtfCodigo.setText(null);
            jlistComponentes.setSelectedIndex(0);
            jtextFieldSemFoco();
        } else {
            JOptionPane.showMessageDialog(null, "O Codigo introduzido ja foi registado.");
        }

        readJTable();
    }//GEN-LAST:event_jbtGravarActionPerformed

    /**
     * butao responsavel por actualizar dados que ja foram gravados na base de dados.
     * @param evt 
     */
    private void jbtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizarActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            Computador b = new Computador();
            ComputadorDAO estu = new ComputadorDAO();
            ArrayList t = new ArrayList();

            int[] selectedIx = this.jlistComponentes.getSelectedIndices();

            for (int i = 0; i < selectedIx.length; i++) {
                t.add(jlistComponentes.getModel().getElementAt(selectedIx[i]));

            }
            b.setDescricao(jtfDescricao.getText());
            b.setCodigo((String) tabela.getValueAt(tabela.getSelectedRow(), 0));
            b.setComponentes(t.toString());
            b.setData((Date) tabela.getValueAt(tabela.getSelectedRow(), 3));
            b.setEstado((String) tabela.getValueAt(tabela.getSelectedRow(), 4));
            if (estu.atualizar(b)) {
                JOptionPane.showMessageDialog(null, "O computador foi actualizado com sucesso");
                jtfDescricao.setText(null);
                jtfCodigo.setText(null);
                jlistComponentes.setSelectedIndex(0);
                jtextFieldSemFoco();
                readJTable();
                setStep(STEP_CRIAR);

            } else {
                JOptionPane.showMessageDialog(null, "O Codigo introduzido ja foi registado!!!");
            }

        }
    }//GEN-LAST:event_jbtActualizarActionPerformed

    /**
     * butao responsavel por remover o objecto na base de dados de uma forma logica.
     * Na remocao muda o estudo do registo para removido
     * @param evt 
     */
    private void jbtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoverActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            Computador a = new Computador();
            ComputadorDAO dau = new ComputadorDAO();
            ArrayList t = new ArrayList();

            int[] selectedIx = this.jlistComponentes.getSelectedIndices();

            for (int i = 0; i < selectedIx.length; i++) {
                t.add(jlistComponentes.getModel().getElementAt(selectedIx[i]));

            }

            int b = JOptionPane.showConfirmDialog(null, "Deseja mesmo remover?");
            if (b == 0) {

                a.setDescricao((String) tabela.getValueAt(tabela.getSelectedRow(),1));
                a.setCodigo((String) tabela.getValueAt(tabela.getSelectedRow(), 0));
                a.setComponentes((String) tabela.getValueAt(tabela.getSelectedRow(), 2));
                a.setEstado(Constantes.ESTADO_REGISTO_REMOVIDO);
                a.setData((Date) tabela.getValueAt(tabela.getSelectedRow(), 3));
               
                dau.atualizar(a);

                JOptionPane.showMessageDialog(null,
                        "Removido com sucesso");
                jtfDescricao.setText(null);
                jtfCodigo.setText(null);
                jlistComponentes.setSelectedIndex(0);
                jtextFieldSemFoco();
                readJTable();
                setStep(STEP_CRIAR);
               
            }

        } else {
            JOptionPane.showMessageDialog(null,
                    "Selecione um computador para poder remover");
        }

    }//GEN-LAST:event_jbtRemoverActionPerformed

    /**
     * butao que faz a pesquisa de um determinado objecto na base de dados.
     * @param evt 
     */
    private void jbrPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrPesquisarActionPerformed
        // TODO add your handling code here:
        readJTable1();
    }//GEN-LAST:event_jbrPesquisarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            jtfDescricao.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            jtfCodigo.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            setStep(STEP_VISUALIZAR);

        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void jPanel5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel5AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5AncestorAdded

    private void jtfDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDescricaoActionPerformed

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void jtfDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescricaoKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfCodigo.requestFocus();
        }
    }//GEN-LAST:event_jtfDescricaoKeyPressed

    private void jtfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyPressed

        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jlistComponentes.requestFocus();
        }
    }//GEN-LAST:event_jtfCodigoKeyPressed

    private void jbtGravarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtGravarKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbtGravarKeyPressed

    private void jtfDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescricaoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDescricaoKeyTyped

    private void jtfDescricaoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtfDescricaoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDescricaoPropertyChange

    private void jlistComponentesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlistComponentesKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jbtGravar.requestFocus();
        }
    }//GEN-LAST:event_jlistComponentesKeyPressed

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed
        // TODO add your handling code here:
        setStep(STEP_EDITAR);
    }//GEN-LAST:event_jbtEditarActionPerformed

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        // TODO add your handling code here:
        int b = JOptionPane.showConfirmDialog(null, "Deseja mesmo voltar?");
        if (b == 0) {
            new RegistarComputador().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbtVoltarActionPerformed

    private void jbtFechar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFechar2ActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtFechar2ActionPerformed

    private void jtfCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfCodigo, "ex: 123M");
    }//GEN-LAST:event_jtfCodigoFocusGained

    private void jtfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusLost
        // TODO add your handling code here:
        perderFoco(jtfCodigo, "ex: 123M");
    }//GEN-LAST:event_jtfCodigoFocusLost

    private void jtfDescricaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDescricaoFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfDescricao, "ex: ");
    }//GEN-LAST:event_jtfDescricaoFocusGained

    private void jtfDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDescricaoFocusLost
        // TODO add your handling code here:
        perderFoco(jtfDescricao, "ex: ");
    }//GEN-LAST:event_jtfDescricaoFocusLost

    private void jbtAvariadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAvariadoActionPerformed
        // TODO add your handling code here:
         if (tabela.getSelectedRow() != -1) {
            Computador a = new Computador();
            ComputadorDAO dau = new ComputadorDAO();

            int b = JOptionPane.showConfirmDialog(null, "Com certeza que o computador esta avariado?");
            if (b == 0) {

                a.setDescricao((String) tabela.getValueAt(tabela.getSelectedRow(),1));
                a.setCodigo((String) tabela.getValueAt(tabela.getSelectedRow(), 0));
                a.setComponentes((String) tabela.getValueAt(tabela.getSelectedRow(), 2));
                a.setEstado(Constantes.ESTADO_REGISTO_AVARIADO);
                a.setData((Date) tabela.getValueAt(tabela.getSelectedRow(), 3));
               
                dau.atualizar(a);

                JOptionPane.showMessageDialog(null,
                        "O computador esta avariado.");
                jtfDescricao.setText(null);
                jtfCodigo.setText(null);
                jlistComponentes.setSelectedIndex(0);
                jtextFieldSemFoco();
                readJTable();
                setStep(STEP_CRIAR);
               
            }
         }                   
    }//GEN-LAST:event_jbtAvariadoActionPerformed

    /**
     * Metodo responsavel por buscar os dados na base de dados e mostrar na tabela.
     */
    public void readJTable() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        ComputadorDAO dau = new ComputadorDAO();

        for (Computador a : dau.consular()) {
            if ((a.getEstado().equalsIgnoreCase(Constantes.ESTADO_REGISTO_VIGOR))) {
                modelo1.addRow(new Object[]{a.getCodigo(), a.getDescricao(),
                    a.getComponentes(), a.getData()

                });
            }

        }
    }

    /**
     * Metodo responsavel buscar os dados pesquisados e mostrar na tabela.
     */
    public void readJTable1() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        ComputadorDAO dau = new ComputadorDAO();

        for (Computador a : dau.consular()) {
            if (a.getCodigo().equalsIgnoreCase(jtfCodigo.getText())) {

                modelo1.addRow(new Object[]{a.getCodigo(), a.getDescricao(),
                    a.getComponentes(), a.getData(), a.getEstado()

                });
            }
        }
    }

    /**
     * metodo que ajuda a desabilitar alguns campos e butoes na tela.
     * @param step 
     */
    public void setStep(String step) {

        if (step.equalsIgnoreCase(STEP_CRIAR)) {
            jbtGravar.setVisible(true);
            jbrPesquisar.setVisible(true);
            jbtLimpar.setVisible(true);
            jbtActualizar.setVisible(false);
            jbtEditar.setVisible(false);
            jbtRemover.setVisible(false);
            jbtAvariado.setVisible(false);
            jbtVoltar.setVisible(false);
            jtfDescricao.setEnabled(true);
            jtfCodigo.setEnabled(true);
            jlistComponentes.setEnabled(true);

        } else if (step.equalsIgnoreCase(STEP_VISUALIZAR)) {
            jbtGravar.setVisible(false);
            jbrPesquisar.setVisible(false);
            jbtLimpar.setVisible(false);
            jbtActualizar.setVisible(false);
            jbtEditar.setVisible(true);
            jbtRemover.setVisible(true);
            jbtAvariado.setVisible(true);
            jbtVoltar.setVisible(true);
            jtfDescricao.setEnabled(false);
            jtfCodigo.setEnabled(false);
            jlistComponentes.setEnabled(false);

        } else if (step.equalsIgnoreCase(STEP_EDITAR)) {
            jbtGravar.setVisible(false);
            jbrPesquisar.setVisible(false);
            jbtLimpar.setVisible(true);
            jbtActualizar.setVisible(true);
            jbtEditar.setVisible(false);
            jbtRemover.setVisible(false);
            jbtAvariado.setVisible(false);
            jbtVoltar.setVisible(true);
            jtfDescricao.setEnabled(true);
            jtfCodigo.setEnabled(false);
            jlistComponentes.setEnabled(true);
        }
    }

    private void ganharFocus(JTextField tf, String s) {
        if (tf.getText().equals(s)) {
            tf.setText("");
        }
    }

    private void perderFoco(JTextField tf, String s) {
        if (tf.getText().equals("")) {
            tf.setText(s);
        }
    }

    private void jtextFieldSemFoco() {
        jtfCodigo.setText("ex: 123M");
        jtfDescricao.setText("ex: ");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbrPesquisar;
    private javax.swing.JButton jbtActualizar;
    private javax.swing.JButton jbtAvariado;
    private javax.swing.JButton jbtEditar;
    private javax.swing.JButton jbtFechar2;
    private javax.swing.JButton jbtGravar;
    private javax.swing.JButton jbtLimpar;
    private javax.swing.JButton jbtRemover;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JList<String> jlistComponentes;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblComponentes;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblRegistoComputador;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
