/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Controle.DocenteDAO;
import Modelo.Docente;
import Modelo.Salas;
import Controle.SalasDAO;
import Modelo.Constantes;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JTextField;

/**
 * Tela que faz o registo de um docente.
 * @author 
 * @version 1.0
 */
public class RegistarDocente extends javax.swing.JFrame {

    private static final String STEP_CRIAR = "Criar";
    public static final String STEP_VISUALIZAR = "Visualizar";
    private static final String STEP_EDITAR = "Editar";

    /**
     * Creates new form
     */
    public RegistarDocente() {

        initComponents();
         Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize = (int) tk.getScreenSize().getWidth();
                int ysize = (int) tk.getScreenSize().getHeight();
         this.setSize(xsize,ysize);
        jtextFieldSemFoco();
        readJTable();
        adcionarSalaDocente();
        setStep(STEP_CRIAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblRegistoDocente = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbtFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfCodigo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jcbSala = new javax.swing.JComboBox<>();
        lblSala = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jbtGravar = new javax.swing.JButton();
        jbtActualizar = new javax.swing.JButton();
        jbtEditar = new javax.swing.JButton();
        jbtRemover = new javax.swing.JButton();
        jbrPesquisar = new javax.swing.JButton();
        jbtLimpar = new javax.swing.JButton();
        jbtVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        lblRegistoDocente.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        lblRegistoDocente.setText("REGISTO DO DOCENTE");
        jPanel8.add(lblRegistoDocente);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridLayout(3, 0));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridLayout(0, 10));
        jPanel10.add(jLabel2);
        jPanel10.add(jLabel3);
        jPanel10.add(jLabel4);
        jPanel10.add(jLabel5);
        jPanel10.add(jLabel6);
        jPanel10.add(jLabel7);
        jPanel10.add(jLabel8);
        jPanel10.add(jLabel9);
        jPanel10.add(jLabel10);

        jbtFechar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtFechar.setText("Fechar");
        jbtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharActionPerformed(evt);
            }
        });
        jPanel10.add(jbtFechar);

        jPanel9.add(jPanel10);

        jPanel7.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        jPanel5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel5AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblNome.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblNome.setText("Nome");

        lblCodigo.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblCodigo.setText("Codigo");

        jtfNome.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jtfNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNomeFocusLost(evt);
            }
        });
        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });
        jtfNome.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtfNomePropertyChange(evt);
            }
        });
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomeKeyTyped(evt);
            }
        });

        jtfCodigo.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jtfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusLost(evt);
            }
        });
        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });
        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jtfCodigo))
                .addGap(170, 170, 170))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        jPanel6.setLayout(null);

        jcbSala.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jcbSala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbSalaKeyPressed(evt);
            }
        });
        jPanel6.add(jcbSala);
        jcbSala.setBounds(160, 10, 240, 40);

        lblSala.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblSala.setText("Sala");
        jPanel6.add(lblSala);
        lblSala.setBounds(50, 10, 70, 33);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new java.awt.BorderLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Sala", "Data"
            }
        ));
        tabela.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jbtGravar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtGravar.setText("Gravar");
        jbtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGravarActionPerformed(evt);
            }
        });
        jbtGravar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtGravarKeyPressed(evt);
            }
        });
        jPanel4.add(jbtGravar);

        jbtActualizar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtActualizar.setText("Actualizar");
        jbtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtActualizar);

        jbtEditar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtEditar.setText("Editar");
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtEditar);

        jbtRemover.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtRemover.setText("Remover");
        jbtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoverActionPerformed(evt);
            }
        });
        jPanel4.add(jbtRemover);

        jbrPesquisar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbrPesquisar.setText("Pesquisar");
        jbrPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrPesquisarActionPerformed(evt);
            }
        });
        jPanel4.add(jbrPesquisar);

        jbtLimpar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtLimpar.setText("Limpar");
        jbtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimparActionPerformed(evt);
            }
        });
        jPanel4.add(jbtLimpar);

        jbtVoltar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtVoltar.setText("Voltar");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtVoltar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void tabelaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaAncestorAdded

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            jtfNome.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            jtfCodigo.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            jcbSala.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
            setStep(STEP_VISUALIZAR);

        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void jbtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jbtFecharActionPerformed

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        // TODO add your handling code here:
        int b = JOptionPane.showConfirmDialog(null, "Deseja mesmo voltar?");
        if (b == 0) {
            new RegistarDocente().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbtVoltarActionPerformed

    /**
     * butao responsavel por limpar os dados na tela
     * @param evt 
     */
    private void jbtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimparActionPerformed
        // TODO add your handling code here:
        int b = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar?");
        if (b == 0) {
            jtfNome.setText(null);
            jtfCodigo.setText(null);
            jcbSala.setSelectedIndex(0);
            jtextFieldSemFoco();
            readJTable();
        }
    }//GEN-LAST:event_jbtLimparActionPerformed

    /**
     * butao que faz a pesquisa de um determinado objecto na base de dados.
     * @param evt 
     */
    private void jbrPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrPesquisarActionPerformed
        // TODO add your handling code here:
        readJTable1();
    }//GEN-LAST:event_jbrPesquisarActionPerformed

    /**
     * butao responsavel por remover o objecto ba base de dados de uma forma logica.
     * Na remocao muda o estudo do registo para removido 
     * @param evt 
     */
    private void jbtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoverActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            Docente a = new Docente();
            DocenteDAO dau = new DocenteDAO();

            int b = JOptionPane.showConfirmDialog(null, "Deseja mesmo remover?");
            if (b == 0) {
                a.setNome((String) tabela.getValueAt(tabela.getSelectedRow(), 1));
                a.setCodigo((Integer) tabela.getValueAt(tabela.getSelectedRow(), 0));
                a.setSala((Salas) tabela.getValueAt(tabela.getSelectedRow(), 2));
                a.setEstado(Constantes.ESTADO_REGISTO_REMOVIDO);
                a.setData((Date) tabela.getValueAt(tabela.getSelectedRow(), 3));

                dau.atualizar(a);
                JOptionPane.showMessageDialog(null,
                    "Removido com sucesso");
                jtfNome.setText(null);
                jtfCodigo.setText(null);
                jcbSala.setSelectedIndex(0);
                jtextFieldSemFoco();
                readJTable();
                setStep(STEP_CRIAR);

            } else {
                JOptionPane.showMessageDialog(null,
                    "Selecione um docente para poder remover");
            }
        }
    }//GEN-LAST:event_jbtRemoverActionPerformed

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed
        // TODO add your handling code here:
        setStep(STEP_EDITAR);
    }//GEN-LAST:event_jbtEditarActionPerformed

    /**
     * butao responsavel por actualizar dados que ja foram gravados na base de dados.
     * @param evt 
     */
    private void jbtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizarActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            Docente b = new Docente();

            DocenteDAO estu = new DocenteDAO();

            b.setNome(jtfNome.getText());
            b.setCodigo(Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(), 0).toString()));
            b.setSala((Salas) jcbSala.getSelectedItem());
            b.setData((Date) tabela.getValueAt(tabela.getSelectedRow(), 3));
            b.setEstado((String) tabela.getValueAt(tabela.getSelectedRow(), 4));
            if (estu.atualizar(b)) {
                JOptionPane.showMessageDialog(null, "O docente foi actualizado com sucesso");
                jtfNome.setText(null);
                jtfCodigo.setText(null);
                jcbSala.setSelectedIndex(0);
                jtextFieldSemFoco();
                readJTable();
                setStep(STEP_CRIAR);
            } else {
                JOptionPane.showMessageDialog(null, "Nao foi possivel actualizar o docente!!!");
            }

        }
    }//GEN-LAST:event_jbtActualizarActionPerformed

    private void jbtGravarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtGravarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtGravarKeyPressed

    /**
     * butao responsavel por gravar os dados na base dados.
     * @param evt 
     */
    private void jbtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGravarActionPerformed
        // TODO add your handling code here:
        Docente b = new Docente();

        DocenteDAO estu = new DocenteDAO();
        int contador = 0;
        for (Docente a : estu.consular()) {
            if (a.getCodigo() == Integer.parseInt(jtfCodigo.getText())) {
                contador++;
            }
        }
        if (contador == 0) {
            b.setNome(jtfNome.getText());
            b.setCodigo(Integer.parseInt((jtfCodigo.getText())));
            Salas saladocente = (Salas) jcbSala.getSelectedItem();
            b.setSala(saladocente);
            b.setEstado(Constantes.ESTADO_REGISTO_VIGOR);
            b.setData(new Date());

            estu.gravar(b);

            JOptionPane.showMessageDialog(null, "O docente foi registado com sucesso");
            jtfNome.setText(null);
            jtfCodigo.setText(null);
            jcbSala.setSelectedIndex(0);
            jtextFieldSemFoco();
            readJTable();
        } else {
            JOptionPane.showMessageDialog(null, "O Codigo introduzido ja foi registado.");
        }

    }//GEN-LAST:event_jbtGravarActionPerformed

    private void jcbSalaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbSalaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jbtGravar.requestFocus();
        }
    }//GEN-LAST:event_jcbSalaKeyPressed

    private void jPanel5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel5AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5AncestorAdded

    private void jtfCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfCodigoKeyTyped

    private void jtfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyPressed

        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jcbSala.requestFocus();
        }
    }//GEN-LAST:event_jtfCodigoKeyPressed

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void jtfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusLost
        // TODO add your handling code here:
        perderFoco(jtfCodigo, "ex: 1234567");
    }//GEN-LAST:event_jtfCodigoFocusLost

    private void jtfCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfCodigo, "ex: 1234567");
    }//GEN-LAST:event_jtfCodigoFocusGained

    private void jtfNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfNomeKeyTyped

    private void jtfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfCodigo.requestFocus();
        }
    }//GEN-LAST:event_jtfNomeKeyPressed

    private void jtfNomePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtfNomePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomePropertyChange

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    private void jtfNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNomeFocusLost
        // TODO add your handling code here:
        perderFoco(jtfNome, "ex: Helvecio Lumenta");
    }//GEN-LAST:event_jtfNomeFocusLost

    private void jtfNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNomeFocusGained
        // TODO add your handling code here:
        ganharFocus(jtfNome, "ex: Helvecio Lumenta");
    }//GEN-LAST:event_jtfNomeFocusGained

    /**
     * metodo que adciona todas salas dos docentes registadas na combo box sala 
     * para o registo de um  docente.
     */
    public void adcionarSalaDocente() {
        SalasDAO dao = new SalasDAO();
        for (Salas t : dao.consular()) {
            if ((t.getEstado().equalsIgnoreCase(Constantes.ESTADO_REGISTO_VIGOR))&&((t.getCategoria().equalsIgnoreCase("Docente")))) {
                jcbSala.addItem(t);
            }
        }
    }

    /**
     * Metodo responsavel por buscar os dados na base de dados e mostrar na tabela.
     */
    public void readJTable() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        DocenteDAO dau = new DocenteDAO();

        for (Docente a : dau.consular()) {
            if ((a.getEstado().equalsIgnoreCase(Constantes.ESTADO_REGISTO_VIGOR))) {

                modelo1.addRow(new Object[]{a.getCodigo(), a.getNome(),
                    a.getSala(), a.getData()

                });

            }
        }
    }

    /**
     * Metodo responsavel buscar os dados pesquisados e mostrar na tabela.
     */
    public void readJTable1() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        DocenteDAO dau = new DocenteDAO();

        for (Docente a : dau.consular()) {
            if (a.getNome().equalsIgnoreCase(jtfNome.getText())) {

                    modelo1.addRow(new Object[]{a.getCodigo(), a.getNome(),
                        a.getSala(), a.getData()

                    });
                }
        }
            
    }

    /**
     * metodo que ajuda a desabilitar alguns campos e butoes na tela.
     * @param step 
     */
    public void setStep(String step) {

        if (step.equalsIgnoreCase(STEP_CRIAR)) {
            jbtGravar.setVisible(true);
            jbrPesquisar.setVisible(true);
            jbtLimpar.setVisible(true);
            jbtActualizar.setVisible(false);
            jbtEditar.setVisible(false);
            jbtRemover.setVisible(false);
            jbtVoltar.setVisible(false);
            jtfNome.setEnabled(true);
            jtfCodigo.setEnabled(true);
            jcbSala.setEnabled(true);

        } else if (step.equalsIgnoreCase(STEP_VISUALIZAR)) {
            jbtGravar.setVisible(false);
            jbrPesquisar.setVisible(false);
            jbtLimpar.setVisible(false);
            jbtActualizar.setVisible(false);
            jbtEditar.setVisible(true);
            jbtRemover.setVisible(true);
            jbtVoltar.setVisible(true);
            jtfNome.setEnabled(false);
            jtfCodigo.setEnabled(false);
            jcbSala.setEnabled(false);

        } else if (step.equalsIgnoreCase(STEP_EDITAR)) {
            jbtGravar.setVisible(false);
            jbrPesquisar.setVisible(false);
            jbtLimpar.setVisible(true);
            jbtActualizar.setVisible(true);
            jbtEditar.setVisible(false);
            jbtRemover.setVisible(false);
            jbtVoltar.setVisible(false);
            jtfNome.setEnabled(true);
            jtfCodigo.setEnabled(false);
            jcbSala.setEnabled(true);
        }
    }

    private void ganharFocus(JTextField tf, String s) {
        if (tf.getText().equals(s)) {
            tf.setText("");
        }
    }

    private void perderFoco(JTextField tf, String s) {
        if (tf.getText().equals("")) {
            tf.setText(s);
        }
    }

    private void jtextFieldSemFoco() {
        jtfCodigo.setText("ex: 1234567");
        jtfNome.setText("ex: Joao Metambo");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbrPesquisar;
    private javax.swing.JButton jbtActualizar;
    private javax.swing.JButton jbtEditar;
    private javax.swing.JButton jbtFechar;
    private javax.swing.JButton jbtGravar;
    private javax.swing.JButton jbtLimpar;
    private javax.swing.JButton jbtRemover;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JComboBox<Modelo.Salas> jcbSala;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRegistoDocente;
    private javax.swing.JLabel lblSala;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
