/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Visao.TelaPrincipal;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Classe responsvel pela permicao de requisicao e divulcao do material.
 * @author 
 */
public class Requisicoes extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio_Material
     */
    public Requisicoes() {
        initComponents();
        btnAdm.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelDeCima = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelDeBaixo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        entrarRequisitarMaterial = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAdm = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        entrarDevolverMaterial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REQUISIÇÕES");
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        painelPrincipal.setLayout(new java.awt.BorderLayout());

        painelDeCima.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REQUISIÇÕES");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        painelDeCima.add(jLabel1);

        painelPrincipal.add(painelDeCima, java.awt.BorderLayout.PAGE_START);

        painelDeBaixo.setBackground(new java.awt.Color(255, 255, 255));
        painelDeBaixo.setLayout(new java.awt.GridLayout(3, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel2.setText("REQUISITAR MATERIAL");
        jPanel1.add(jLabel2);

        entrarRequisitarMaterial.setBackground(new java.awt.Color(102, 102, 102));
        entrarRequisitarMaterial.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        entrarRequisitarMaterial.setText("Entrar");
        entrarRequisitarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarRequisitarMaterialActionPerformed(evt);
            }
        });
        jPanel1.add(entrarRequisitarMaterial);

        painelDeBaixo.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnAdm.setFont(new java.awt.Font("DialogInput", 3, 24)); // NOI18N
        btnAdm.setText("ADM");
        btnAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdm);

        painelDeBaixo.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel3.setText("DEVOLVER MATERIAL  ");
        jPanel3.add(jLabel3);

        entrarDevolverMaterial.setBackground(new java.awt.Color(102, 102, 102));
        entrarDevolverMaterial.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        entrarDevolverMaterial.setText("Entrar");
        entrarDevolverMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarDevolverMaterialActionPerformed(evt);
            }
        });
        jPanel3.add(entrarDevolverMaterial);

        painelDeBaixo.add(jPanel3);

        painelPrincipal.add(painelDeBaixo, java.awt.BorderLayout.CENTER);

        getContentPane().add(painelPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
 * butao que chama a tela para requistar o material
 * @param evt 
 */
    private void entrarRequisitarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarRequisitarMaterialActionPerformed
       
        new TelaRequisitarMaterial().setVisible(true);
        this.setVisible(false);
            
    }//GEN-LAST:event_entrarRequisitarMaterialActionPerformed

    /**
     * butao que chama a tela para devolver o material
     * @param evt 
     */
    private void entrarDevolverMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarDevolverMaterialActionPerformed
        // TODO add your handling code here:
        new TelaDevolverMaterial().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_entrarDevolverMaterialActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        btnAdm.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * butao que chama o login do administrador.
     * @param evt 
     */
    private void btnAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmActionPerformed
        // TODO add your handling code here:
        new LoginAdministrador().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdmActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdm;
    private javax.swing.JButton entrarDevolverMaterial;
    private javax.swing.JButton entrarRequisitarMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel painelDeBaixo;
    private javax.swing.JPanel painelDeCima;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
