/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controle.ReservarSalaDAO;
import Controle.FuncionarioDAO;
import Controle.DocenteDAO;
import Controle.SalasDAO;
import Modelo.Constantes;
import Modelo.Salas;
import Modelo.ReservarSala;
import Modelo.Docente;
import Modelo.Funcionario;
import Modelo.Material;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JTextField;

/**
 * Tela responsavel por reservar uma determinada sala.
 * @author 
 * @version 1.0
 */
public class TelaReservarSala extends javax.swing.JFrame {

    private static final String STEP_CRIAR = "Criar";
    public static final String STEP_VISUALIZAR = "Visualizar";
    private static final String STEP_EDITAR = "Editar";

    /**
     * Creates new form
     */
    public TelaReservarSala() {

        initComponents();
         Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize = (int) tk.getScreenSize().getWidth();
                int ysize = (int) tk.getScreenSize().getHeight();
         this.setSize(xsize,ysize);
        readJTable();
        adcionarDocente();
        adcionarFuncionario();
        adcionarSala();
        setStep(STEP_CRIAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblRequisitarMaterial = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbtFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblNomeDocente = new javax.swing.JLabel();
        jcbNomeDocentes = new javax.swing.JComboBox<>();
        lblNomeFuncionarios = new javax.swing.JLabel();
        jcbNomeFuncionarios = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        lblSala = new javax.swing.JLabel();
        jcbSalas = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jbtReservar = new javax.swing.JButton();
        jbtActualizar = new javax.swing.JButton();
        jbtEditar = new javax.swing.JButton();
        jbrPesquisar = new javax.swing.JButton();
        jbtLimpar = new javax.swing.JButton();
        jbtVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        lblRequisitarMaterial.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        lblRequisitarMaterial.setText("RESERVAR SALA");
        jPanel8.add(lblRequisitarMaterial);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridLayout(3, 0));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridLayout(0, 10));
        jPanel10.add(jLabel2);
        jPanel10.add(jLabel3);
        jPanel10.add(jLabel4);
        jPanel10.add(jLabel5);
        jPanel10.add(jLabel6);
        jPanel10.add(jLabel7);
        jPanel10.add(jLabel8);
        jPanel10.add(jLabel9);
        jPanel10.add(jLabel10);

        jbtFechar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtFechar.setText("Fechar");
        jbtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharActionPerformed(evt);
            }
        });
        jPanel10.add(jbtFechar);

        jPanel9.add(jPanel10);

        jPanel7.add(jPanel9, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel7);

        jPanel5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel5AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblNomeDocente.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblNomeDocente.setText("Nome Doc.");
        lblNomeDocente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblNomeDocenteKeyPressed(evt);
            }
        });

        jcbNomeDocentes.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jcbNomeDocentes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbNomeDocentesKeyPressed(evt);
            }
        });

        lblNomeFuncionarios.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblNomeFuncionarios.setText("Nome Func.");

        jcbNomeFuncionarios.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jcbNomeFuncionarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbNomeFuncionariosKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeFuncionarios)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblNomeDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbNomeFuncionarios, 0, 310, Short.MAX_VALUE)
                            .addComponent(jcbNomeDocentes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeDocente)
                    .addComponent(jcbNomeDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeFuncionarios)
                    .addComponent(jcbNomeFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanel6.setLayout(null);

        lblSala.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblSala.setText("Sala");
        lblSala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblSalaKeyPressed(evt);
            }
        });
        jPanel6.add(lblSala);
        lblSala.setBounds(20, 10, 56, 33);

        jcbSalas.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jcbSalas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbSalasKeyPressed(evt);
            }
        });
        jPanel6.add(jcbSalas);
        jcbSalas.setBounds(150, 10, 280, 39);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new java.awt.BorderLayout());

        tabela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Docente", "Nome Funcionario", "Sala Reservada", "Data"
            }
        ));
        tabela.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jbtReservar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtReservar.setText("Reservar");
        jbtReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtReservarActionPerformed(evt);
            }
        });
        jbtReservar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtReservarKeyPressed(evt);
            }
        });
        jPanel4.add(jbtReservar);

        jbtActualizar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtActualizar.setText("Actualizar");
        jbtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtActualizar);

        jbtEditar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtEditar.setText("Editar");
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtEditar);

        jbrPesquisar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbrPesquisar.setText("Pesquisar");
        jbrPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrPesquisarActionPerformed(evt);
            }
        });
        jPanel4.add(jbrPesquisar);

        jbtLimpar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtLimpar.setText("Limpar");
        jbtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimparActionPerformed(evt);
            }
        });
        jPanel4.add(jbtLimpar);

        jbtVoltar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtVoltar.setText("Voltar");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtVoltar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * butao responsavel por limpar os dados na tela
     * @param evt 
     */
    private void jbtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimparActionPerformed
        // TODO add your handling code here:
        int b = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar?");
        if (b == 0) {
            jcbNomeDocentes.setSelectedIndex(0);
            jcbSalas.setSelectedIndex(0);
            jcbNomeFuncionarios.setSelectedIndex(0);
            readJTable();
        }
    }//GEN-LAST:event_jbtLimparActionPerformed

    private void jcbNomeFuncionariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbNomeFuncionariosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jcbSalas.requestFocus();
        }
    }//GEN-LAST:event_jcbNomeFuncionariosKeyPressed

    private void tabelaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaAncestorAdded

    /**
     * butao responsavel por reservar um determinado material.
     * @param evt 
     */
    private void jbtReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtReservarActionPerformed
        // TODO add your handling code here:
        ReservarSala b = new ReservarSala();
        ReservarSalaDAO estu = new ReservarSalaDAO();
        
        int contador=0;
        for(ReservarSala reservar: estu.consultar() ){
              if(reservar.getSalas().equals(jcbSalas.getSelectedItem()))
               contador++;
              
        }

        if(contador==0){
        Docente docente = (Docente) jcbNomeDocentes.getSelectedItem();
        b.setDocentes(docente);
        Funcionario funcionario = (Funcionario) jcbNomeFuncionarios.getSelectedItem();
        b.setNomefuncionario(funcionario);
        Salas salas = (Salas) jcbSalas.getSelectedItem(); 
        b.setSalas(salas);
        b.setEstado(Constantes.ESTADO_REGISTO_RESERVADO);
        b.setData(new Date());

        estu.gravar(b);
            JOptionPane.showMessageDialog(null, "A sala foi reservda com sucesso");
            jcbNomeDocentes.setSelectedIndex(0);
            jcbNomeFuncionarios.setSelectedIndex(0);
            jcbSalas.setSelectedIndex(0);
            readJTable();
        } else {
            JOptionPane.showMessageDialog(null, "Nao foi possivel reservar a sala!!!.");
        }

     
    }//GEN-LAST:event_jbtReservarActionPerformed

    private void jbtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizarActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            ReservarSala b = new ReservarSala();
            ReservarSalaDAO estu = new ReservarSalaDAO();
            
            b.setDocentes((Docente) jcbNomeDocentes.getSelectedItem());
            b.setNomefuncionario((Funcionario) jcbNomeFuncionarios.getSelectedItem());
            b.setSalas((Salas) jcbSalas.getSelectedItem());
            b.setData((Date) tabela.getValueAt(tabela.getSelectedRow(), 3));
            b.setEstado(Constantes.ESTADO_REGISTO_RESERVADO);

            if (estu.atualizar(b)) {
                JOptionPane.showMessageDialog(null, "Actualizacao efectuada com sucesso");
                jcbNomeFuncionarios.setSelectedIndex(0);
                jcbNomeFuncionarios.setSelectedIndex(0);
                jcbSalas.setSelectedIndex(0);
                readJTable();
                setStep(STEP_CRIAR);

            } else {
                JOptionPane.showMessageDialog(null, "Nao foi possivel actualizar a reserva!!!");
            }

        }
    }//GEN-LAST:event_jbtActualizarActionPerformed

    /**
     * butao que faz a pesquisa de um determinado objecto na base de dados.
     * @param evt 
     */
    private void jbrPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrPesquisarActionPerformed
        // TODO add your handling code here:
        readJTable1();
    }//GEN-LAST:event_jbrPesquisarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            setStep(STEP_VISUALIZAR);
            jcbNomeDocentes.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            jcbNomeFuncionarios.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            jcbSalas.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
           
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void jPanel5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel5AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5AncestorAdded

    private void jbtReservarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtReservarKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbtReservarKeyPressed

    private void lblNomeDocenteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblNomeDocenteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNomeDocenteKeyPressed

    private void jcbNomeDocentesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbNomeDocentesKeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jcbNomeFuncionarios.requestFocus();
        }
    }//GEN-LAST:event_jcbNomeDocentesKeyPressed

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed
        // TODO add your handling code here:
        setStep(STEP_EDITAR);
    }//GEN-LAST:event_jbtEditarActionPerformed

    private void jbtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jbtFecharActionPerformed

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        // TODO add your handling code here:
        int b = JOptionPane.showConfirmDialog(null, "Deseja mesmo voltar?");
        if (b == 0) {
            new TelaReservarSala().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbtVoltarActionPerformed

    private void lblSalaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblSalaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSalaKeyPressed

    private void jcbSalasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbSalasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbSalasKeyPressed

    /**
     * metodo que adciona todos funcionario registadas na combo box nomefuncionarios 
     * para a requisicao de um material
     */
    public void adcionarFuncionario() {
        FuncionarioDAO dao = new FuncionarioDAO();
        for (Funcionario t : dao.consular()) {
            if ((t.getEstado().equalsIgnoreCase(Constantes.ESTADO_REGISTO_VIGOR))) {
                jcbNomeFuncionarios.addItem(t);
            }
        }
    }

    /**
     * metodo que adciona todos estudantes registadas na combo box nomeestudantes 
     * para a requisicao de um material
     */
    public void adcionarDocente() {
        DocenteDAO dao = new DocenteDAO();
        for (Docente t : dao.consular()) {
          if ((t.getEstado().equalsIgnoreCase(Constantes.ESTADO_REGISTO_VIGOR))) {
            jcbNomeDocentes.addItem(t);
          }
        }
    }
    public void adcionarSala() {
        SalasDAO dao = new SalasDAO();
        for (Salas t : dao.consular()) {
          if ((t.getEstado().equalsIgnoreCase(Constantes.ESTADO_REGISTO_VIGOR))&&(t.getCategoria().equalsIgnoreCase("Simples")||t.getCategoria().equalsIgnoreCase("Laboratorio"))) {
            jcbSalas.addItem(t);
          }
        }
    }

    /**
     * Metodo responsavel por buscar os dados na base de dados e mostrar na tabela.
     */
    public void readJTable() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        ReservarSalaDAO dau = new ReservarSalaDAO();

        for (ReservarSala a : dau.consultar()) {
            if ((a.getEstado().equalsIgnoreCase(Constantes.ESTADO_REGISTO_RESERVADO))) {
                modelo1.addRow(new Object[]{ a.getDocentes(),
                    a.getNomefuncionario(), a.getSalas(), a.getData(),a.getCod_reserva()

                });
            }
        }
    }

    /**
     * Metodo responsavel buscar os dados pesquisados e mostrar na tabela.
     */
    public void readJTable1() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        ReservarSalaDAO dau = new ReservarSalaDAO();

        for (ReservarSala a : dau.consultar()) {
            if (a.getDocentes().equals(jcbNomeDocentes.getSelectedItem())||a.getSalas().equals((Salas) jcbSalas.getSelectedItem())) {

                modelo1.addRow(new Object[]{a.getDocentes(),
                    a.getNomefuncionario(), a.getSalas(), a.getData()

                });
            }
        }
    }

    /**
     * metodo que ajuda a desabilitar alguns campos e butoes na tela.
     * @param step 
     */
    public void setStep(String step) {

        if (step.equalsIgnoreCase(STEP_CRIAR)) {
            jbtReservar.setVisible(true);
            jbrPesquisar.setVisible(true);
            jbtLimpar.setVisible(true);
            jbtActualizar.setVisible(false);
            jbtEditar.setVisible(false);
            jbtVoltar.setVisible(false);
            jcbNomeDocentes.setEnabled(true);
            jcbNomeFuncionarios.setEnabled(true);
            jcbSalas.setEnabled(true);

        } else if (step.equalsIgnoreCase(STEP_VISUALIZAR)) {
            jbtReservar.setVisible(false);
           
            jbrPesquisar.setVisible(false);
            jbtLimpar.setVisible(false);
            jbtActualizar.setVisible(false);
            jbtEditar.setVisible(true);
            jbtVoltar.setVisible(true);
            jcbNomeDocentes.setEnabled(false);
            jcbNomeFuncionarios.setEnabled(false);
            jcbSalas.setEnabled(false);
           

        } else if (step.equalsIgnoreCase(STEP_EDITAR)) {
            jbtReservar.setVisible(false);
            jbrPesquisar.setVisible(false);
            jbtLimpar.setVisible(true);
            jbtActualizar.setVisible(true);
            jbtEditar.setVisible(false);
            jbtVoltar.setVisible(true);
            jcbNomeDocentes.setEnabled(true);
            jcbNomeFuncionarios.setEnabled(true);
            jcbSalas.setEnabled(true);
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbrPesquisar;
    private javax.swing.JButton jbtActualizar;
    private javax.swing.JButton jbtEditar;
    private javax.swing.JButton jbtFechar;
    private javax.swing.JButton jbtLimpar;
    private javax.swing.JButton jbtReservar;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JComboBox<Docente> jcbNomeDocentes;
    private javax.swing.JComboBox<Funcionario> jcbNomeFuncionarios;
    private javax.swing.JComboBox<Salas> jcbSalas;
    private javax.swing.JLabel lblNomeDocente;
    private javax.swing.JLabel lblNomeFuncionarios;
    private javax.swing.JLabel lblRequisitarMaterial;
    private javax.swing.JLabel lblSala;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
