/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Relatorios.RelatorioComputador;
import Relatorios.RelatorioEstudante;
import Relatorios.RelatorioMaterial;
import java.awt.Color;
import java.awt.Toolkit;

/**
 * Tela principal
 * @author 
 * @version 1.0
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize = (int) tk.getScreenSize().getWidth();
                int ysize = (int) tk.getScreenSize().getHeight();
         this.setSize(xsize,ysize);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCentral = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jmMenu = new javax.swing.JMenuBar();
        jmRegistar = new javax.swing.JMenu();
        jmiEstudante = new javax.swing.JMenuItem();
        jmiFuncionarios = new javax.swing.JMenuItem();
        jmiMaterias = new javax.swing.JMenuItem();
        jmiComputadores = new javax.swing.JMenuItem();
        jmiDocentes = new javax.swing.JMenuItem();
        jmiSalaDocentes = new javax.swing.JMenuItem();
        jmMateriais = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiRelatorioComputador = new javax.swing.JMenuItem();
        jmiRelatorioEstudante = new javax.swing.JMenuItem();
        jmiRelatorioMaterial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TELA DO ADMINISTRADOR");

        PainelCentral.setBackground(new java.awt.Color(0, 204, 51));
        PainelCentral.setPreferredSize(new java.awt.Dimension(900, 600));
        PainelCentral.setLayout(new javax.swing.BoxLayout(PainelCentral, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eee.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        PainelCentral.add(jLabel2);

        getContentPane().add(PainelCentral, java.awt.BorderLayout.CENTER);

        jmMenu.setBackground(new java.awt.Color(255, 255, 255));
        jmMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jmMenu.setDoubleBuffered(true);
        jmMenu.setFocusCycleRoot(true);
        jmMenu.setFocusTraversalPolicyProvider(true);

        jmRegistar.setText("Registar   |");
        jmRegistar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jmRegistar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jmRegistarMouseEntered(evt);
            }
        });

        jmiEstudante.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jmiEstudante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-icon.png"))); // NOI18N
        jmiEstudante.setText("Estudantes");
        jmiEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEstudanteActionPerformed(evt);
            }
        });
        jmRegistar.add(jmiEstudante);

        jmiFuncionarios.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jmiFuncionarios.setText("Funcionários");
        jmiFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFuncionariosActionPerformed(evt);
            }
        });
        jmRegistar.add(jmiFuncionarios);

        jmiMaterias.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jmiMaterias.setText("Materiais");
        jmiMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMateriasActionPerformed(evt);
            }
        });
        jmRegistar.add(jmiMaterias);

        jmiComputadores.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jmiComputadores.setText("Computadores");
        jmiComputadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiComputadoresActionPerformed(evt);
            }
        });
        jmRegistar.add(jmiComputadores);

        jmiDocentes.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jmiDocentes.setText("Docentes");
        jmiDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDocentesActionPerformed(evt);
            }
        });
        jmRegistar.add(jmiDocentes);

        jmiSalaDocentes.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jmiSalaDocentes.setText("Salas e Laboratorios");
        jmiSalaDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalaDocentesActionPerformed(evt);
            }
        });
        jmRegistar.add(jmiSalaDocentes);

        jmMenu.add(jmRegistar);

        jmMateriais.setText("Sala     |");
        jmMateriais.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jmMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMateriaisActionPerformed(evt);
            }
        });

        jMenuItem2.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jMenuItem2.setText("Reservar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmMateriais.add(jMenuItem2);

        jMenuItem4.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jMenuItem4.setText("Devolver");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jmMateriais.add(jMenuItem4);

        jmMenu.add(jmMateriais);

        jMenu1.setText("Relatorios                          ");
        jMenu1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N

        jmiRelatorioComputador.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jmiRelatorioComputador.setText("Computador");
        jmiRelatorioComputador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioComputadorActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelatorioComputador);

        jmiRelatorioEstudante.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jmiRelatorioEstudante.setText("Estudante");
        jmiRelatorioEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioEstudanteActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelatorioEstudante);

        jmiRelatorioMaterial.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jmiRelatorioMaterial.setText("Material");
        jmiRelatorioMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioMaterialActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRelatorioMaterial);

        jmMenu.add(jMenu1);

        setJMenuBar(jmMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * butao que chama tela registar estudante.
     * @param evt 
     */
    private void jmiEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEstudanteActionPerformed
        // TODO add your handling code here:
        RegistarEstudant r = new RegistarEstudant();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiEstudanteActionPerformed

    /**
     * butao que chama tela registar computador.
     * @param evt 
     */
    private void jmiComputadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiComputadoresActionPerformed
        // TODO add your handling code here:
        new RegistarComputador().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiComputadoresActionPerformed

    /**
     * butao que chama tela registar docente.
     * @param evt 
     */
    private void jmiDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDocentesActionPerformed
        // TODO add your handling code here:
        new RegistarDocente().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jmiDocentesActionPerformed

    private void jmRegistarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmRegistarMouseEntered
        // TODO add your handling code here:
       jmiEstudante.setVisible(true);
       jmiDocentes.setVisible(true);
       jmiComputadores.setVisible(true);
       jmiFuncionarios.setVisible(true);
       jmiSalaDocentes.setVisible(true);
       jmiMaterias.setVisible(true);
    }//GEN-LAST:event_jmRegistarMouseEntered

    /**
     * butao que chama tela registar funcionario.
     * @param evt 
     */
    private void jmiFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFuncionariosActionPerformed
        // TODO add your handling code here:
        new RegistarFuncionario().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiFuncionariosActionPerformed

    /**
     * butao que chama tela registar material.
     * @param evt 
     */
    private void jmiMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMateriasActionPerformed
        // TODO add your handling code here:
        new RegistarMaterial().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jmiMateriasActionPerformed

    /**
     * butao que chama tela registar sala docentes.
     * @param evt 
     */
    private void jmiSalaDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalaDocentesActionPerformed
        // TODO add your handling code here:
         new RegistarSalas().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jmiSalaDocentesActionPerformed

    private void jmMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMateriaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmMateriaisActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new TelaReservarSala().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmiRelatorioComputadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioComputadorActionPerformed
        // TODO add your handling code here:
        new RelatorioComputador().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiRelatorioComputadorActionPerformed

    private void jmiRelatorioEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioEstudanteActionPerformed
        // TODO add your handling code here:
        new RelatorioEstudante().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiRelatorioEstudanteActionPerformed

    private void jmiRelatorioMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioMaterialActionPerformed
        // TODO add your handling code here:
        new RelatorioMaterial().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiRelatorioMaterialActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here
        new TelaDevolverSala().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCentral;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jmMateriais;
    private javax.swing.JMenuBar jmMenu;
    private javax.swing.JMenu jmRegistar;
    private javax.swing.JMenuItem jmiComputadores;
    private javax.swing.JMenuItem jmiDocentes;
    private javax.swing.JMenuItem jmiEstudante;
    private javax.swing.JMenuItem jmiFuncionarios;
    private javax.swing.JMenuItem jmiMaterias;
    private javax.swing.JMenuItem jmiRelatorioComputador;
    private javax.swing.JMenuItem jmiRelatorioEstudante;
    private javax.swing.JMenuItem jmiRelatorioMaterial;
    private javax.swing.JMenuItem jmiSalaDocentes;
    // End of variables declaration//GEN-END:variables
}
