/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controle.RequisitarMaterialDAO;
import Controle.FuncionarioDAO;
import Controle.EstudanteDAO;
import Controle.MarerialDAO;
import Modelo.Constantes;
import Modelo.RequisitarMaterial;
import Modelo.Estudante;
import Modelo.Funcionario;
import Modelo.Material;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 * Tela responsavel por requisitar um determinado material.
 * @author 
 * @version 1.0
 */
public class TelaRequisitarMaterial extends javax.swing.JFrame {

    private static final String STEP_CRIAR = "Criar";
    public static final String STEP_VISUALIZAR = "Visualizar";
    private static final String STEP_EDITAR = "Editar";
    DefaultListModel modeloLista;

    /**
     * Creates new form
     */
    public TelaRequisitarMaterial() {
        initComponents();
         Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize = (int) tk.getScreenSize().getWidth();
                int ysize = (int) tk.getScreenSize().getHeight();
         this.setSize(xsize,ysize);
        readJTable();
        modeloLista = new DefaultListModel();
        jlistMaterialRequistado.setModel(modeloLista);
        adcionarEstudante();
        adcionarMaterial();
        adcionarFuncionario();
        setStep(STEP_CRIAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblRequisitarMaterial = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbtFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblNomeEstudantes = new javax.swing.JLabel();
        jcbNomeEstudantes = new javax.swing.JComboBox<>();
        lblNomeFuncionarios = new javax.swing.JLabel();
        jcbNomeFuncionarios = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        lblMaterialRequisitado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistMaterialRequistado = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jbtRequisitar = new javax.swing.JButton();
        jbtActualizar = new javax.swing.JButton();
        jbtEditar = new javax.swing.JButton();
        jbrPesquisar = new javax.swing.JButton();
        jbtLimpar = new javax.swing.JButton();
        jbtVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        lblRequisitarMaterial.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        lblRequisitarMaterial.setText("REQUISITTAR MATERIAL");
        jPanel8.add(lblRequisitarMaterial);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridLayout(3, 0));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridLayout(0, 10));
        jPanel10.add(jLabel2);
        jPanel10.add(jLabel3);
        jPanel10.add(jLabel4);
        jPanel10.add(jLabel5);
        jPanel10.add(jLabel6);
        jPanel10.add(jLabel7);
        jPanel10.add(jLabel8);
        jPanel10.add(jLabel9);
        jPanel10.add(jLabel10);

        jbtFechar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtFechar.setText("Fechar");
        jbtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharActionPerformed(evt);
            }
        });
        jPanel10.add(jbtFechar);

        jPanel9.add(jPanel10);

        jPanel7.add(jPanel9, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel7);

        jPanel5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel5AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblNomeEstudantes.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblNomeEstudantes.setText("Nome Est.");
        lblNomeEstudantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblNomeEstudantesKeyPressed(evt);
            }
        });

        jcbNomeEstudantes.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jcbNomeEstudantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbNomeEstudantesKeyPressed(evt);
            }
        });

        lblNomeFuncionarios.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblNomeFuncionarios.setText("Nome Func.");

        jcbNomeFuncionarios.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jcbNomeFuncionarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbNomeFuncionariosKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbNomeEstudantes, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbNomeFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblNomeEstudantes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFuncionarios))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeEstudantes)
                    .addComponent(jcbNomeEstudantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeFuncionarios)
                    .addComponent(jcbNomeFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanel6.setLayout(null);

        lblMaterialRequisitado.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lblMaterialRequisitado.setText("Material Req.");
        jPanel6.add(lblMaterialRequisitado);
        lblMaterialRequisitado.setBounds(30, 10, 190, 33);

        jlistMaterialRequistado.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jlistMaterialRequistado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlistMaterialRequistadoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jlistMaterialRequistado);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(240, 0, 260, 150);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new java.awt.BorderLayout());

        tabela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Material", "Nome Estudante", "Nome Funcionario", "Material Requisitado", "Data"
            }
        ));
        tabela.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jbtRequisitar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtRequisitar.setText("Requisitar");
        jbtRequisitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRequisitarActionPerformed(evt);
            }
        });
        jbtRequisitar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtRequisitarKeyPressed(evt);
            }
        });
        jPanel4.add(jbtRequisitar);

        jbtActualizar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtActualizar.setText("Actualizar");
        jbtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtActualizar);

        jbtEditar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtEditar.setText("Editar");
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtEditar);

        jbrPesquisar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbrPesquisar.setText("Pesquisar");
        jbrPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrPesquisarActionPerformed(evt);
            }
        });
        jPanel4.add(jbrPesquisar);

        jbtLimpar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtLimpar.setText("Limpar");
        jbtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimparActionPerformed(evt);
            }
        });
        jPanel4.add(jbtLimpar);

        jbtVoltar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jbtVoltar.setText("Voltar");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtVoltar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * butao responsavel por limpar os dados na tela
     * @param evt 
     */
    private void jbtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimparActionPerformed
        // TODO add your handling code here:
        int b = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar?");
        if (b == 0) {
            jcbNomeEstudantes.setSelectedIndex(0);
            jlistMaterialRequistado.setSelectedIndex(0);
            jcbNomeFuncionarios.setSelectedIndex(0);
            readJTable();
        }
    }//GEN-LAST:event_jbtLimparActionPerformed

    private void jcbNomeFuncionariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbNomeFuncionariosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jlistMaterialRequistado.requestFocus();
        }
    }//GEN-LAST:event_jcbNomeFuncionariosKeyPressed

    private void tabelaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaAncestorAdded

    /**
     * butao responsavel por requisitar um determinado material.
     * @param evt 
     */
    private void jbtRequisitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRequisitarActionPerformed
        // TODO add your handling code here:
        RequisitarMaterial b = new RequisitarMaterial();
        RequisitarMaterialDAO estu = new RequisitarMaterialDAO();
        ArrayList t = new ArrayList();

        int[] selectedIx = this.jlistMaterialRequistado.getSelectedIndices();

        for (int i = 0; i < selectedIx.length; i++) {
            t.add(jlistMaterialRequistado.getModel().getElementAt(selectedIx[i]));

        }

        Estudante estudante = (Estudante) jcbNomeEstudantes.getSelectedItem();
        b.setNomeestudante(estudante);
        Funcionario funcionario = (Funcionario) jcbNomeFuncionarios.getSelectedItem();
        b.setNomefuncionario(funcionario);
        b.setMaterialrequisitado(t.toString());
        b.setEstado(Constantes.ESTADO_REGISTO_EMPRESTADO);
        b.setData(new Date());

        if (estu.gravar(b)) {
            JOptionPane.showMessageDialog(null, "O Material foi requisitado com sucesso");
            jcbNomeFuncionarios.setSelectedIndex(0);
            jcbNomeFuncionarios.setSelectedIndex(0);
            jlistMaterialRequistado.setSelectedIndex(0);
            readJTable();
        } else {
            JOptionPane.showMessageDialog(null, "Nao foi possivel requistar o material!!!.");
        }

     
    }//GEN-LAST:event_jbtRequisitarActionPerformed

    private void jbtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizarActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            RequisitarMaterial b = new RequisitarMaterial();
            RequisitarMaterialDAO estu = new RequisitarMaterialDAO();
            ArrayList t = new ArrayList();

            int[] selectedIx = this.jlistMaterialRequistado.getSelectedIndices();

            for (int i = 0; i < selectedIx.length; i++) {
                t.add(jlistMaterialRequistado.getModel().getElementAt(selectedIx[i]));

            }

            b.setCodigo(Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(), 0).toString()));
            b.setNomeestudante((Estudante) tabela.getValueAt(tabela.getSelectedRow(), 1));
            b.setNomefuncionario((Funcionario) tabela.getValueAt(tabela.getSelectedRow(), 2));
            b.setMaterialrequisitado(t.toString());
            b.setData((Date) tabela.getValueAt(tabela.getSelectedRow(), 4));
            b.setEstado((String) tabela.getValueAt(tabela.getSelectedRow(), 5));

            if (estu.atualizar(b)) {
                JOptionPane.showMessageDialog(null, "Actualizacao efectuada com sucesso");
                jcbNomeFuncionarios.setSelectedIndex(0);
                jcbNomeFuncionarios.setSelectedIndex(0);
                jlistMaterialRequistado.setSelectedIndex(0);
                readJTable();
                setStep(STEP_CRIAR);

            } else {
                JOptionPane.showMessageDialog(null, "Nao foi possivel actualizar a requisicao!!!");
            }

        }
    }//GEN-LAST:event_jbtActualizarActionPerformed

    /**
     * butao que faz a pesquisa de um determinado objecto na base de dados.
     * @param evt 
     */
    private void jbrPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrPesquisarActionPerformed
        // TODO add your handling code here:
        readJTable1();
    }//GEN-LAST:event_jbrPesquisarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
          
            jcbNomeEstudantes.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            jcbNomeFuncionarios.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
            setStep(STEP_VISUALIZAR);

        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void jPanel5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel5AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5AncestorAdded

    private void jbtRequisitarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtRequisitarKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbtRequisitarKeyPressed

    private void lblNomeEstudantesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblNomeEstudantesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNomeEstudantesKeyPressed

    private void jcbNomeEstudantesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbNomeEstudantesKeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jcbNomeFuncionarios.requestFocus();
        }
    }//GEN-LAST:event_jcbNomeEstudantesKeyPressed

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed
        // TODO add your handling code here:
        setStep(STEP_EDITAR);
    }//GEN-LAST:event_jbtEditarActionPerformed

    private void jlistMaterialRequistadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlistMaterialRequistadoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jbtRequisitar.requestFocus();
        }
    }//GEN-LAST:event_jlistMaterialRequistadoKeyPressed

    private void jbtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharActionPerformed
        // TODO add your handling code here:
        new Requisicoes().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jbtFecharActionPerformed

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        // TODO add your handling code here:
        int b = JOptionPane.showConfirmDialog(null, "Deseja mesmo voltar?");
        if (b == 0) {
            new TelaRequisitarMaterial().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbtVoltarActionPerformed

    /**
     * metodo que adciona todos funcionario registadas na combo box nomefuncionarios 
     * para a requisicao de um material
     */
    public void adcionarFuncionario() {
        FuncionarioDAO dao = new FuncionarioDAO();
        for (Funcionario t : dao.consular()) {
            if ((t.getEstado().equalsIgnoreCase(Constantes.ESTADO_REGISTO_VIGOR))) {
                jcbNomeFuncionarios.addItem(t);
            }
        }
    }

    /**
     * metodo que adciona todos estudantes registadas na combo box nomeestudantes 
     * para a requisicao de um material
     */
    public void adcionarEstudante() {
        EstudanteDAO dao = new EstudanteDAO();
        for (Estudante t : dao.consular()) {
          if ((t.getEstado().equalsIgnoreCase(Constantes.ESTADO_REGISTO_VIGOR))) {
            jcbNomeEstudantes.addItem(t);
          }
        }
    }
     public void adcionarMaterial() {
        MarerialDAO dao = new MarerialDAO();
        for (Material t : dao.consular()) {
//          if ((t.getEstado().equalsIgnoreCase(Constantes.ESTADO_REGISTO_VIGOR))) {
              modeloLista.addElement(t);
           
     
//          }
        }
    }

    /**
     * Metodo responsavel por buscar os dados na base de dados e mostrar na tabela.
     */
    public void readJTable() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        RequisitarMaterialDAO dau = new RequisitarMaterialDAO();

        for (RequisitarMaterial a : dau.consultar()) {
            if ((a.getEstado().equalsIgnoreCase(Constantes.ESTADO_REGISTO_EMPRESTADO))) {
                modelo1.addRow(new Object[]{a.getCodigo(), a.getNomeestudante(),
                    a.getNomefuncionario(), a.getMaterialrequisitado(), a.getData()

                });
            }
        }
    }

    /**
     * Metodo responsavel buscar os dados pesquisados e mostrar na tabela.
     */
    public void readJTable1() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        RequisitarMaterialDAO dau = new RequisitarMaterialDAO();

        for (RequisitarMaterial a : dau.consultar()) {
            if (a.getNomeestudante().equals((Estudante) jcbNomeEstudantes.getSelectedItem())) {

                modelo1.addRow(new Object[]{a.getCodigo(), a.getNomeestudante(),
                    a.getNomefuncionario(), a.getMaterialrequisitado(), a.getData()

                });
            }
        }
    }

    /**
     * metodo que ajuda a desabilitar alguns campos e butoes na tela.
     * @param step 
     */
    public void setStep(String step) {

        if (step.equalsIgnoreCase(STEP_CRIAR)) {
            jbtRequisitar.setVisible(true);
            jbrPesquisar.setVisible(true);
            jbtLimpar.setVisible(true);
            jbtActualizar.setVisible(false);
            jbtEditar.setVisible(false);
            jbtVoltar.setVisible(false);
            jcbNomeEstudantes.setEnabled(true);
            jcbNomeFuncionarios.setEnabled(true);
            jlistMaterialRequistado.setEnabled(true);

        } else if (step.equalsIgnoreCase(STEP_VISUALIZAR)) {
            jbtRequisitar.setVisible(false);
           
            jbrPesquisar.setVisible(false);
            jbtLimpar.setVisible(false);
            jbtActualizar.setVisible(false);
            jbtEditar.setVisible(true);
            jbtVoltar.setVisible(true);
            jcbNomeEstudantes.setEnabled(false);
            jcbNomeFuncionarios.setEnabled(false);
            jlistMaterialRequistado.setEnabled(false);
           

        } else if (step.equalsIgnoreCase(STEP_EDITAR)) {
            jbtRequisitar.setVisible(false);
            jbrPesquisar.setVisible(false);
            jbtLimpar.setVisible(true);
            jbtActualizar.setVisible(true);
            jbtEditar.setVisible(false);
            jbtVoltar.setVisible(true);
            jcbNomeEstudantes.setEnabled(false);
            jcbNomeFuncionarios.setEnabled(false);
            jlistMaterialRequistado.setEnabled(true);
   
        }
    }

 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
/*
Metódo para mudar o estilo da tela 
JTATO lookAndFeel usado
             */
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
                //                tema castanho para o Look and Feel
                UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                //                Tema do Java
                //            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
                //                Mudar o look and fell do JBuldier ide
                //                 UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
                //                   UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
                //       UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");

            



}

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAcesso.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        



} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAcesso.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        



} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAcesso.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        



} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAcesso.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistarMaterial().setVisible(true);
            }
        });
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbrPesquisar;
    private javax.swing.JButton jbtActualizar;
    private javax.swing.JButton jbtEditar;
    private javax.swing.JButton jbtFechar;
    private javax.swing.JButton jbtLimpar;
    private javax.swing.JButton jbtRequisitar;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JComboBox<Estudante> jcbNomeEstudantes;
    private javax.swing.JComboBox<Funcionario> jcbNomeFuncionarios;
    private javax.swing.JList<Material> jlistMaterialRequistado;
    private javax.swing.JLabel lblMaterialRequisitado;
    private javax.swing.JLabel lblNomeEstudantes;
    private javax.swing.JLabel lblNomeFuncionarios;
    private javax.swing.JLabel lblRequisitarMaterial;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
